spring:
    h2:
        console:
            enabled: true
            path: /h2_console
    datasource:
        url: jdbc:h2:file:~/h2/dolphindb
        username: sa
        password: 
        driverClassName: org.h2.Driver
    jpa:
        hibernate:
            ddl-auto: update
        show-sql: true